name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - sqlalchemy
  - pymysql
  - pip
  - pip:
    - torch==2.3.0   #using pip for torch & torchtext
    - torchtext==0.18.0
